"""fix user id

Revision ID: 13c2d38c246a
Revises: f05faf219d3a
Create Date: 2025-02-27 07:23:58.831954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c2d38c246a'
down_revision: Union[str, None] = 'f05faf219d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('UserId', sa.UUID(), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_UserId'), 'users', ['UserId'], unique=False)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_UserId'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'UserId')
    # ### end Alembic commands ###
