"""add graph tables

Revision ID: d88dc14d1a51
Revises: 3000a6e48a83
Create Date: 2025-03-04 06:22:18.706072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88dc14d1a51'
down_revision: Union[str, None] = '3000a6e48a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExcelFiles',
    sa.Column('ExcelFileId', sa.Integer(), nullable=False),
    sa.Column('FileName', sa.String(), nullable=True),
    sa.Column('FileContent', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('ExcelFileId')
    )
    op.create_table('GraphImages',
    sa.Column('GraphImageId', sa.Integer(), nullable=False),
    sa.Column('ExcelFileId', sa.Integer(), nullable=True),
    sa.Column('GraphType', sa.String(), nullable=True),
    sa.Column('ImageContent', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['ExcelFileId'], ['ExcelFiles.ExcelFileId'], ),
    sa.PrimaryKeyConstraint('GraphImageId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GraphImages')
    op.drop_table('ExcelFiles')
    # ### end Alembic commands ###
