"""Alter users table

Revision ID: f05faf219d3a
Revises: 
Create Date: 2025-02-27 07:06:41.657916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05faf219d3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('HashedPassword', sa.String(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsArchived', sa.Boolean(), nullable=True),
    sa.Column('ArchivedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ArchivedBy', sa.String(length=100), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_active', 'users', ['Email', 'IsActive'], unique=False)
    op.create_index(op.f('ix_users_Email'), 'users', ['Email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_Email'), table_name='users')
    op.drop_index('idx_email_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
